### ISSUE TITLE
First impression thoughts

### ISSUE THREAD

**Issue by DannyBen** [nanoc/nanoc.app#258]
Hey guys,

Love nanoc and the nanoc site. Seems super easy to use, and with good sensible engineering behind it.

My first initial thoughts are these:

1. The search filter on the nanoc website does not seem to work.
2. Now that we have GitHub Discussions, perhaps it would be a better place for community discussions, instead of the Google Groups, which looks like an incarnation of mailing lists?
3. ~This bullet probably does not belong here, but I am on a roll: Is there support for slim templates instead of ERB? slim is much friendlier. I guess I can write one myself, but still, I wish I could just do `layout '/**/*', :slim`~ - ... sorry, found it!

**Comment by ddfreyne** [comment]
Hey, thanks for the feedback!

* The search is working in the mean time, and #264 also updates to the most recent version of DocSearch. That should keep it going for a while longer.

* Google Groups and Gitter are still the go-to places for discussion, though I’ve also opened up the discussion on https://github.com/nanoc/nanoc.
