### ISSUE TITLE
Missing Space?

### ISSUE THREAD

**Issue by henk84** [nanoc/nanoc.app#285]
https://github.com/nanoc/nanoc.app/blob/1417c58e66f3071676b5c1517e43e33d7d78f26b/content/doc/tutorial.dmark#L81 looks correct in the source but on https://nanoc.app/doc/tutorial/ it comes out as:
```
<em>not</em><span class=productname>asdf</span>!
```
i.e. with a missing space.

**Comment by denisdefreyne** [comment]
Thanks for pointing this out! Fixed in 04c7206874afc8054378c96def23ca082fd1213d -- `htmlcompressor` was the culprit and I removed it (seems unmaintained).
